import "./globals.css";
import type { Metadata } from "next";
import Providers from "@/providers";

export const metadata: Metadata = {
  title: "HF - E-commerce",
  description: "Generated by HeadFord",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
